name: Generate Rust Documentation

on:
  push:
    branches:
      - master
permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Generate Documentation
      run: cargo doc --no-deps --manifest-path ./rust_server/Cargo.toml 
    - name: Fix paths
      run: echo "<meta http-equiv=\"refresh\" content=\"0; url=rust_server\">" > ./rust_server/target/doc/index.html

      
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.8
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: docs
        folder: ./rust_server/target/doc/rust_server
        clean: true
        git-config-email: bot@swc.rs
        repository-name: SaremS/quarto_paywall
        commit-message: "Update"
        single-commit: true
