name: Generate Rust Documentation

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Generate Documentation
      run: cargo doc --no-deps --manifest-path ./rust_server/Cargo.toml 
    - name: Move static files
      run: mv ./rust_server/target/doc/static.files/ ./rust_server/target/doc/rust_server/static.files/
    - name: Create Jekyll config
      run: touch ./rust_server/target/doc/rust_server/.nojekyll
      
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.8
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: docs
        folder: ./rust_server/target/doc/rust_server
        clean: true
        git-config-email: bot@swc.rs
        repository-name: SaremS/quarto_paywall
        commit-message: "Update"
        single-commit: true
