name: Generate Rust Documentation

on:
  push:
    branches:
      - master

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Generate Documentation
      run: cd rust_server && cargo doc --no-deps

    - name: Deploy Documentation
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git fetch origin
        git checkout docs || git checkout -b docs
        cp -r ./rust_server/target/doc/* .
        git add .
        git commit -m "Update documentation"
        git push origin docs
